FROM adoptopenjdk/openjdk13-openj9:latest
MAINTAINER openslice.io
ENV SPRING_APPLICATION_JSON='{ \
	"spring.datasource.url": "dbc:mysql://10.0.2.15/ostmfdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",  \
	"spring.activemq.broker-url": "tcp://10.0.2.15:61616"  }'
RUN mkdir /opt/shareclasses
RUN mkdir -p /opt/openslice/lib/
COPY target/io.openslice.oas-1.0.2-SNAPSHOT-exec.jar /opt/openslice/lib/
CMD ["java", "-Xshareclasses:cacheDir=/opt/shareclasses", "-jar", "/opt/openslice/lib/io.openslice.oas-1.0.2-SNAPSHOT-exec.jar"]
EXPOSE 13101